export const SET_SOLUTION = 'SET_SOLUTION';

export const SET_PUZZLED = 'SET_PUZZLED';

export const INIT_VALIDATION = 'INIT_VALIDATION';
export const CHECK_VALIDATION = 'CHECK_VALIDATION';
export const UNCHECK_VALIDATION = 'UNCHECK_VALIDATION';

export const INIT_VALUE = 'INIT_VALUE';
export const SET_VALUE = 'SET_VALUE';

export const SET_CUR_GRID = 'SET_CUR_GRID';
export const CLEAR_CUR_GRID = 'CLEAR_CUR_GRID';

export const SET_MINI_SHOWN = 'SET_MINI_SHOWN';

export const SET_SUCCESS_SHOWN = 'SET_SUCCESS_SHOWN';

export const SET_DIFFICULTY = 'SET_DIFFICULTY';